### ISSUE TITLE
Remove dependency on sinatra & thin

### ISSUE THREAD

**Issue by tigris** [jhchabran/photograph#10]
I'm only interested in using Photograph::Artist, not ::Service, so having the Gemfile pull in sinatra/thin and all of their dependencies is overkill.

**Comment by jhchabran** [comment]
Yeah, the Sinatra dependency is clearly overkill and can be removed easily, I'll extract it to another gem.

**Comment by jhchabran** [comment]
Done, it had been extracted to https://github.com/jhchabran/photograph-service
Thin and Sinatra had been removed. 

I'll push it on RubyGems.org once I've added some deprecation message. Until then, using the master branch will do the job.
