### ISSUE TITLE
Ruby 2.0.0 failure.

### ISSUE THREAD

**Issue by preston** [jhchabran/photograph#7]
2.0.0p247 :002 > @artist = Photograph::Artist.new("http://github.com")
TypeError: no implicit conversion of Symbol into Integer
    from /Users/preston/.rvm/gems/ruby-2.0.0-p247/gems/photograph-0.0.2/lib/photograph/artist.rb:32:in `[]'

**Comment by jhchabran** [comment]
There's an error in the Readme about instanciating an Artist. The correct way is : 

``` ruby
Photograph::Artist.new(:url => "http://github.com") 
```

The readme had been updated, thanks for reporting the issue.

**Comment by preston** [comment]
Oh awesome, thanks!
