### ISSUE TITLE
Re-use browser session

### ISSUE THREAD

**Issue by tigris** [jhchabran/photograph#8]
I am working on something that needs to authenticate before it can screenshot. Something like the following works perfectly:

``` ruby
module Photograph
  class AuthenticatableArtist < Artist
    def initialize options = {}
      super options
      [:login_page, :username_field, :password_field, :submit_button, :username, :password].each do |option|
        @options[option] = options[option]
      end 
    end 

    def capture
      browser.visit @options[:login_page]
      browser.fill_in(@options[:username_field], with: @options[:username])
      browser.fill_in(@options[:password_field], with: @options[:password])
      browser.click_button @options[:submit_button]
      super
    end 
  end 
end
```

However, it obviously executes that capture block for every "shoot". I wonder if it would be nicer to somehow allow "browser" to be passed in at initialize time, or manipulated via an attr_accessor or similar. It might be tricky though as it does open up implementation detail (that of using capybara under the hood to do the browsing).

This would also require browser to be a pure instance variable and not a class variable. Then it would be pretty easy to just leave `Photograph::Artist` objects "open" in some kind of background worker which would leave the browser session intact whilst other objects could be instantiated and shot without blowing away someone elses browser session?

**Comment by jhchabran** [comment]
The browser should be an instance variable anyway, having it like it's currently done is a bad idea as it usually get in the way if you try to do anything more than a basic usage, as you highlighted :)

The browser should be given to the Artist while instanciating it, allowing to do things like you're doing there. To avoid leaving too much implementations details into the wild, `Photograph.capture` could be added to wrap browser instanciation. 

I was thinking about maybe adding a block parameter to the Artist#new, so you can pilot the browser somewhere before actually taking the screenshot. It appears to me that a such usage is quite common. 

I'll have a look at that soon, I haven't touched this gem in ages, it's time to do some dust cleaning :D

**Comment by jhchabran** [comment]
By the way, I'm happy to see that someone is using this gem, thanks for posting your issue !

**Comment by jhchabran** [comment]
See https://github.com/jhchabran/photograph/commit/53eb03a1f2a569403f7aee2e8e4a7bb1d9f40b78
